"""File Manager module manifest — tool definitions."""

from shared.schemas.tools import ModuleManifest, ToolDefinition, ToolParameter

MANIFEST = ModuleManifest(
    module_name="file_manager",
    description="Manage files in cloud storage. Create, upload, list, retrieve, and delete documents and files.",
    tools=[
        ToolDefinition(
            name="file_manager.create_document",
            description=(
                "Create a new text document and store it. Returns the public URL. "
                "Supports many formats: markdown, plain text, JSON, CSV, HTML, Python, JS, YAML, SQL, and more."
            ),
            parameters=[
                ToolParameter(name="title", type="string", description="Document title (used as filename)"),
                ToolParameter(name="content", type="string", description="Document content"),
                ToolParameter(
                    name="format",
                    type="string",
                    description="File format/extension",
                    required=False,
                    enum=["md", "txt", "json", "csv", "html", "xml", "yaml", "py", "js", "ts", "css", "sql", "sh", "toml", "ini", "log", "svg"],
                ),
            ],
            required_permission="guest",
        ),
        ToolDefinition(
            name="file_manager.upload_file",
            description=(
                "Upload a binary file (image, PDF, etc.) from base64-encoded data. "
                "Use this for files generated by code execution (plots, images, spreadsheets)."
            ),
            parameters=[
                ToolParameter(name="filename", type="string", description="Filename with extension (e.g. chart.png, report.pdf)"),
                ToolParameter(name="data_base64", type="string", description="Base64-encoded file content"),
            ],
            required_permission="guest",
        ),
        ToolDefinition(
            name="file_manager.read_document",
            description="Read the contents of a previously stored text document. Returns the full text content.",
            parameters=[
                ToolParameter(name="file_id", type="string", description="The file record ID"),
            ],
            required_permission="guest",
        ),
        ToolDefinition(
            name="file_manager.list_files",
            description="List all stored files for the current user.",
            parameters=[],
            required_permission="guest",
        ),
        ToolDefinition(
            name="file_manager.get_file_link",
            description="Get the public download URL for a stored file.",
            parameters=[
                ToolParameter(name="file_id", type="string", description="The file record ID"),
            ],
            required_permission="guest",
        ),
        ToolDefinition(
            name="file_manager.delete_file",
            description="Delete a file from storage.",
            parameters=[
                ToolParameter(name="file_id", type="string", description="The file record ID"),
            ],
            required_permission="user",
        ),
    ],
)
